### ISSUE TITLE
Range 184.22.0.0 - 184.22.255.255 false positive

### ISSUE THREAD

**Issue by Ythan** [client9/ipcat#119]
Hi, you have 184.22.0.0/16 flagged as a datacenter owned by http://www.hostnoc.net/, however it's been reported to me that this is a false positive and these IPs are in use by residential customers. The range actually appears to belong to ais.co.th, a Thai mobile data provider.

**Comment by shawnps** [comment]
Thanks for reporting. I've removed that /16.
