### ISSUE TITLE
U.S. Dept. of Commerce range

### ISSUE THREAD

**Issue by rb2k** [client9/ipcat#12]
I'd love to see this one get added to the list :)

NetRange:       170.110.0.0 - 170.110.255.255
CIDR:           170.110.0.0/16
OrgName:        U.S. Dept. of Commerce - ITA

**Comment by shawnps** [comment]
Trying to do some ticket cleanup and I'm not really seeing proof that this is a DC range. If I'm wrong please reopen and discuss.
