### ISSUE TITLE
Missing Server Network Technologies, Inc

### ISSUE THREAD

**Issue by sleptor** [client9/ipcat#133]
https://myip.ms/view/web_hosting/364527/Server_Network_Technologies_Inc.html

104.248.0.0 - 104.248.255.255 
104.233.0.0 - 104.233.63.255
45.43.128.0 - 45.43.191.255
104.222.160.0 - 104.222.191.255 
104.239.0.0 - 104.239.127.255
104.167.0.0 - 104.167.15.255

**Comment by shawnps** [comment]
@sleptor thanks for these. I'm doing some digging now... it looks like this is their website:

http://www.hoststore.com/

At least, that's where I get redirected to when I try to go to servernetwork.com.
