### ISSUE TITLE
datacenters added for FireHOL IP Lists

### ISSUE THREAD

**Issue by ktsaou** [client9/ipcat#137]
Hi,

thank you for maintaining this IP feed.

I have just added it to FireHOL IP Lists at https://iplists.firehol.org/?ipset=datacenters

On that site you can see its geographic coverage and how it correlates to other publicly available IP Feeds.
As time passes and this list gets updated, the site will also track its progress, changesets and retention policy.

Thank you!

**Comment by shawnps** [comment]
@ktsaou Interesting, thanks for the update! Pretty cool to see the GeoLite map.

**Comment by ktsaou** [comment]
yes, even more interesting is to see how datacenters overlap with attacks, abuse, malware, etc (near the end of the page).
