### ISSUE TITLE
CSV not sorted correctly according to IpDbGenerate.php

### ISSUE THREAD

**Issue by wouterhund** [client9/ipcat#15]
When attempting to use the script, it outputs the following:
```
Array
(
    [_ip0] => -2143170560
    [_ip1] => -2143166465
    [owner] => http://www.link11.de/
)
```

This appears to be because `$last1 >= $i0` evaluates to true.

**Comment by client9** [comment]
32-bit PHP.
not fixing.

**Comment by wouterhund** [comment]
Maybe clarify in the readme that 32 bit PHP is not supported?
