### ISSUE TITLE
Missing AWS ranges

### ISSUE THREAD

**Issue by jimdigriz** [client9/ipcat#80]
https://ip-ranges.amazonaws.com/ip-ranges.json contains a number of EC2 marked ranges but they do not appear in your `datacenters.csv` file.

For example (this was found at a large with my log data):

35.160.0.0/13
54.153.0.0/17
54.200.0.0/15

Do you manually update the `datacenters.csv`?  Can I do anything to help?

**Comment by shawnps** [comment]
Hi @jimdigriz

The file is manually updated but we have a make target for automatically pulling down the latest AWS range so and adding them to datacenters.csv

Could you pull the latest and run "make aws" and see if it gets those ranges into the file? If so please make a PR and I'll merge. If it doesn't work  I'll investigate. Thanks!

**Comment by shawnps** [comment]
(Btw this will require your system to have Golang installed. If you don't want that, I'll take a look myself)

**Comment by jimdigriz** [comment]
Hi,

Found the problem, my fault.  `datacentres.csv` is aggregated.

Thanks

**Comment by shawnps** [comment]
No worries, glad it's sorted out!
