### ISSUE TITLE
Cannot run `make generate`

### ISSUE THREAD

**Issue by alaz** [client9/ipcat#93]
I've honestly tried to update the stats, but could not –

```
$ make generate
go run ./cmd/ipcat/main.go
# command-line-arguments
cmd/ipcat/main.go:82: undefined: ipcat.DownloadCloudflare
cmd/ipcat/main.go:86: undefined: ipcat.UpdateCloudflare
make: *** [generate] Error 2
```

**Comment by shawnps** [comment]
@alaz is your fork up to date with master? I added those methods recently, and `make generate` works for me locally.

**Comment by alaz** [comment]
yes, it is

```
Alaz-Laptop:ipcat alaz$ git pull upstream master
From github.com:client9/ipcat
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Alaz-Laptop:ipcat alaz$ make 
go run ./cmd/ipcat/main.go
# command-line-arguments
cmd/ipcat/main.go:82: undefined: ipcat.DownloadCloudflare
cmd/ipcat/main.go:86: undefined: ipcat.UpdateCloudflare
make: *** [generate] Error 2
```

Go version 1.8.1 from Mac ports:

```
Alaz-Laptop:ipcat alaz$ go version
go version go1.8.1 darwin/amd64
```

Should I do some extra step for `import "github.com/client9/ipcat"` to work properly / refresh? I don't know Go, but feel the problem may be somewhere here. Should it pick up `*.go` files from the local copy of the repo?

**Comment by shawnps** [comment]
@alaz normally I'd say something might be strange with your `$GOPATH`, but since it's only complaining about the Cloudflare-related methods being missing, I'm not really sure what's going on. Can you grep for those just to make sure they're really in there? And do you have a GOPATH?

**Comment by shawnps** [comment]
@alaz if you're interested in setting up Go properly I can help you out. Otherwise I'll just generate the stats myself, no problem.

**Comment by alaz** [comment]
@shawnps Ok, let's leave it as is. Frankly I have no spare bandwidth to remember and keep Go setup. Thank you!

**Comment by shawnps** [comment]
@alaz no worries!
