### ISSUE TITLE
Adjust csv output

### ISSUE THREAD

**Issue by esckalayd** [client9/ipcat#98]
Is it possible to have another file where the output is displayed without the Name & Domain and a dash or CIDR notation?

For example:
Original
52.249.168.0,52.249.168.255,Microsoft Azure,http://www.windowsazure.com/en-us/

Proposed
52.249.168.0-52.249.168.255
OR
52.249.168.0/24

**Comment by jimdigriz** [comment]
Pipe through sed/awk?

**Comment by shawnps** [comment]
@esckalayd I agree with @jimdigriz, not sure this warrants a separate file. Try this:

`cut -d ',' -f1-2 datacenters.csv | sed 's/,/-/g'`

**Comment by shawnps** [comment]
@esckalayd since this can be done with the above command line quite easily, I don't intend to add a separate file without the DC names and URLs. I hope the command helps with what you're trying to do and feel free to comment with any other questions.
